# Generated by Django 3.2.12 on 2022-05-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='name',
            new_name='update',
        ),
        migrations.RenameField(
            model_name='publications',
            old_name='name',
            new_name='update',
        ),
        migrations.RenameField(
            model_name='updates',
            old_name='name',
            new_name='update',
        ),
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.CharField(default='source', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='title', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.CharField(default='url', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publications',
            name='source',
            field=models.CharField(default='source', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publications',
            name='title',
            field=models.CharField(default='title', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publications',
            name='url',
            field=models.CharField(default='url', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updates',
            name='note',
            field=models.CharField(default='note', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updates',
            name='title',
            field=models.CharField(default='title', max_length=200),
            preserve_default=False,
        ),
    ]
