# Generated by Django 3.2.12 on 2022-05-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20220503_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='new',
            field=models.SmallIntegerField(choices=[(0, 'old'), (1, 'new')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publications',
            name='new',
            field=models.SmallIntegerField(choices=[(0, 'old'), (1, 'new')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updates',
            name='new',
            field=models.SmallIntegerField(choices=[(0, 'old'), (1, 'new')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='update',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='publications',
            name='update',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='updates',
            name='update',
            field=models.DateField(),
        ),
    ]
